### ISSUE TITLE
Tools won't get cleanup or get reused

### ISSUE THREAD

**Issue by kanimaru** [alexellis/arkade-get#63]
The action fills up our runner when run couple of time. It creates always new /tmp/arkade-* and then the storage fills up.
What can we do against that? Maybe something with #35?

**Comment by alexellis** [comment]
Hi @kanimaru 

1. Can you define "fills up"? The binaries people tend to pull in are just a few megabytes.
2. Why do you think the arkade-get action is to blame for creating files in /tmp/arkade-* and not arkade itself?
2. Is your /tmp directory being properly managed? What's the OS?
3. And why are you not using [an ephemeral runner solution](https://actuated.dev)? Reusing the same runner is dangerous and causes a lot of unexpected side-effects.

**Comment by kanimaru** [comment]
Sorry was in Vacation.

> Can you define "fills up"? The binaries people tend to pull in are just a few megabytes.

Even couple of megabytes are in sum very heavy especially when multiple projects don't cleanup afterwards.

> Why do you think the arkade-get action is to blame for creating files in /tmp/arkade-* and not arkade itself?

I'm not sure didn't looked deeper into it just saw that there wars tons of /tmp/arkade-* folders that was killing the build maschine

> Is your /tmp directory being properly managed? What's the OS?

I don't know how the Runner is setup. Different Team manages it but I would guess they didn't change much from default installation. It's Ubuntu 20.04.5 LTS

> And why are you not using [an ephemeral runner solution](https://actuated.dev/)? Reusing the same runner is dangerous and 
causes a lot of unexpected side-effects.

I know but I have no other choice I can be happy that I get at least 1 worker to build my stuff. It's bad cooperated decision... don't ask.

But it's OK I just wanted to report that you maybe had a bug that you probably fixed already. I have to swap to another solution. From the new runner I got, I can't connect to the internet without going over a proxy. And Arkade seems not to care about proxies at least I think so. Action responded with a 502 when it tries to install tools. But manually I can pull the tool or arkade with curl. Will now build a Docker Image with the tools I need and use this :/. 

But thx for the response and the fix <3

**Comment by alexellis** [comment]
We've made some changes to try and recover some of the folders, for folks who are not running with ephemeral runners, like yourself.

https://github.com/alexellis/arkade/commit/8f028584fc537ec79e0e1f70d7299ca5107765a8
